### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Newspicel** [playlegend/LegendShowLog#18]
Eure Repository ist nur über Benutzername und Passwort erreichbar. Bis gestern war dies noch anders. Bin nur zufällig auf dieses Projekt gestoßen und wollte euch helfen das andere eure Opensource Software immer noch einfach benutzen können.

**Comment by lusu007** [comment]
Vielen Dank für deinen Hinweis. Wir haben momentan ein Problem mit unserem Repository Server, deshalb ist dieser momentan nicht richtig erreichbar. 

Wir versuchen das Problem so schnell wie möglich zu beheben. Ich melde mich hier, wenn alles wieder wie gewohnt funktioniert :smile:

**Comment by Newspicel** [comment]
Ich selber benutze es ja nicht, wollte nur freundlicherweise darauf hinweisen.

**Comment by lusu007** [comment]
Der Repository Server ist jetzt wieder unter [https://repository.playlegend.net](https://repository.playlegend.net/) erreichbar!
